# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('authors', models.CharField(blank=True, max_length=140, null=True)),
                ('publication', models.CharField(blank=True, max_length=140, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Project')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Project'),
        ),
        migrations.AddField(
            model_name='paper',
            name='variables',
            field=models.ManyToManyField(to='mtnlss.Variable'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Paper'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='var1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='mtnlss.Variable'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='var2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='mtnlss.Variable'),
        ),
        migrations.AddField(
            model_name='answer',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Paper'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Question'),
        ),
    ]
