# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
