# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0002_paper_sample_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='variables',
        ),
        migrations.AddField(
            model_name='varpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Paper'),
        ),
        migrations.AddField(
            model_name='varpaper',
            name='var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtnlss.Variable'),
        ),
    ]
