# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0003_auto_20170526_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='variables',
            field=models.ManyToManyField(related_name='its_paper', through='mtnlss.VarPaper', to='mtnlss.Variable'),
        ),
    ]
