# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0005_auto_20170528_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='varpaper',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='varpaper',
            name='mean',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='varpaper',
            name='sd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'paper')]),
        ),
    ]
