# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0006_auto_20170817_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='varpaper',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='varpaper',
            name='mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='varpaper',
            name='sd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
