# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtnlss', '0008_auto_20170821_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varpaper',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='varpaper',
            name='mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='varpaper',
            name='sd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
